<?php
require __DIR__ . '/backend/common.php';
require_admin();
$counts = [
    'papers' => (int) ($conn->query("SELECT COUNT(*) AS total FROM papers WHERE status = 'pending'")->fetch_assoc()['total'] ?? 0),
    'projects' => (int) ($conn->query("SELECT COUNT(*) AS total FROM projects WHERE approval = 'pending'")->fetch_assoc()['total'] ?? 0),
    'joins' => (int) ($conn->query("SELECT COUNT(*) AS total FROM project_join_requests WHERE status = 'pending'")->fetch_assoc()['total'] ?? 0),
    'resets' => (int) ($conn->query("SELECT COUNT(*) AS total FROM password_resets WHERE token_hash IS NULL OR expires_at IS NULL")->fetch_assoc()['total'] ?? 0),
];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Overview · UIU Research Hub</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="portal.css"><style>.admin-hero{padding:30px;border-radius:20px;background:linear-gradient(135deg,#172033,#374f7e);color:white}.admin-hero h1{margin:0;font-size:36px;letter-spacing:-.04em}.admin-hero p{margin:8px 0 0;color:#d5e2f8}.admin-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-top:18px}.admin-card{padding:21px;border:1px solid #e5e9f0;border-radius:16px;background:white}.admin-card strong{display:block;color:#2457d6;font-size:30px}.admin-card span{color:#667085;font-size:13px}.admin-card a{display:inline-block;margin-top:14px;color:#2457d6;font-size:13px;font-weight:700;text-decoration:none}@media(max-width:850px){.admin-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){.admin-grid{grid-template-columns:1fr}}</style></head><body class="portal-page"><div class="app-container portal-layout"><?php require __DIR__ . '/backend/sidebar.php'; ?><main class="main-content"><div class="live-content"><?php show_message(); ?><section class="admin-hero"><p class="eyebrow">ADMINISTRATION</p><h1>Review queue, not clutter.</h1><p>Each operational task has its own focused screen. Start with the queue that needs attention.</p></section><?php require __DIR__ . '/backend/admin_nav.php'; ?><div class="admin-grid"><article class="admin-card"><strong><?= $counts['papers'] ?></strong><span>Papers awaiting editorial review</span><a href="admin-paper-reviews.php">Review papers →</a></article><article class="admin-card"><strong><?= $counts['projects'] ?></strong><span>Projects awaiting approval</span><a href="admin-project-reviews.php">Review projects →</a></article><article class="admin-card"><strong><?= $counts['joins'] ?></strong><span>Project join requests</span><a href="admin-join-requests.php">Review requests →</a></article><article class="admin-card"><strong><?= $counts['resets'] ?></strong><span>Password reset requests</span><a href="admin-password-resets.php">Handle resets →</a></article></div><section class="box"><h2>Administration principles</h2><p>Approvals are deliberate, applicants are notified, and user-account actions are kept separate from research review decisions.</p></section></div></main></div></body></html>
